require.config({
    baseUrl:"/js/",
    paths:{
        //库
        "jquery":"./libs/jquery-2.1.1.min",
        "handlebars":"./libs/handlebars-v4.0.11",
        //app
        "index":"./app/index",
        "render":"./app/render"
    }
})